exclude: ['README.md','assets/latex','assets/ppt']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2025su-cmpt-379-d1/"
semcode: 1254
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Aug 8, 2025"
midterm: "NA"
finalexam: "NA"
instructor: anoop
llvmver: "20.1.x"
llvmconfig: "llvm-config"
tas:
  - name: Mahmoud Abumandour
    email: mam47
    officehour: "Thursdays 09:00-10:00 ASB 9810"
  - name: Sara Babaee Khanehsar
    email: sba236
    officehour: "Fridays 16:00-17:00 ASB 9816"
  - name: Yuehao Hu
    email: yha274
    officehour: "Tuesdays 10:00-11:00 ASB 9810"
hwdates:
  - hw: "0"
    startdate: "May 19, 2025"
    deadline: "May 26, 2025"
    gracedays: "May 28, 2025"
  - hw: "1"
    startdate: "May 26, 2025"
    deadline: "Jun 9, 2025"
    gracedays: "Jun 11, 2025"
  - hw: "2"
    startdate: "Jun 9, 2025"
    deadline: "Jun 23, 2025"
    gracedays: "Jun 25, 2025"
  - hw: "3"
    startdate: "Jun 23, 2025"
    deadline: "Jul 14, 2025"
    gracedays: "Jul 16, 2025"
  - hw: "4"
    startdate: "Jul 14, 2025"
    deadline: "Aug 4, 2025"
    gracedays: "Aug 6, 2025"
  - hw: "5"
    startdate: "Aug 4, 2025"
    deadline: "Aug 11, 2025"
    gracedays: "Aug 13, 2025"
  - hw: "6"
    deadline: "Aug 14, 2025"
    gracedays: "Aug 15, 2025"
quiz:
  - quiz: "0"
    date: "May 21, 2025"
  - quiz: "1"
    date: "Jun 4, 2025"
  - quiz: "2"
    date: "Jun 18, 2025"
  - quiz: "3"
    date: "Jul 9, 2025"
  - quiz: "4"
    date: "Jul 23, 2025"
  - quiz: "5"
    date: "Aug 6, 2025"
